// Auto-generated by .github/workflows/campus-update.yml
// Do NOT hand-edit -- this file is overwritten on each run.
window.CAMPUS_DATA = {
  "generatedAt": "2026-08-20",
  "generatedAtIso": "2026-08-20T04:36:26.651617+00:00",
  "windowSinceDate": "2026-04-01",
  "windowUntilDate": "2026-08-20",
  "campuses": [
    {
      "id": 2637,
      "name": "ACE College of Engineering, Karinkadamugal",
      "district": "thiruvananthapuram",
      "events": 2,
      "types": {
        "Meetup": 1,
        "Learning_Program": 1
      },
      "uniqueAttendees": 4,
      "returning": 0,
      "totalAttendance": 4,
      "members": 61,
      "newFY": 33,
      "stillIn": 58,
      "alumni": 2,
      "gradUnknown": 1,
      "projects": 3
    },
    {
      "id": 2069,
      "name": "Adi Shankara Institute of Engineering and Technology, Mattoor",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 6
      },
      "uniqueAttendees": 27,
      "returning": 6,
      "totalAttendance": 51,
      "members": 675,
      "newFY": 22,
      "stillIn": 620,
      "alumni": 54,
      "gradUnknown": 1,
      "projects": 2
    },
    {
      "id": 2689,
      "name": "Ahalia School of Engineering & Technology, palakkad",
      "district": "palakkad",
      "events": 2,
      "types": {
        "Meetup": 2
      },
      "uniqueAttendees": 34,
      "returning": 8,
      "totalAttendance": 42,
      "members": 101,
      "newFY": 42,
      "stillIn": 94,
      "alumni": 7,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1948,
      "name": "Al Azhar College of Engineering & Technology, Perumpillichira",
      "district": "idukki",
      "events": 3,
      "types": {
        "Talk_Session": 2,
        "Meetup": 1
      },
      "uniqueAttendees": 6,
      "returning": 0,
      "totalAttendance": 6,
      "members": 45,
      "newFY": 36,
      "stillIn": 37,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2070,
      "name": "Albertian Institute of Science and Technology (AISAT), Kalamassery",
      "district": "ernakulam",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 603,
      "newFY": 34,
      "stillIn": 533,
      "alumni": 67,
      "gradUnknown": 3,
      "projects": 9
    },
    {
      "id": 1651,
      "name": "Ansar Women's College, Perumpilavu",
      "district": "thrissur",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Meetup": 2
      },
      "uniqueAttendees": 72,
      "returning": 7,
      "totalAttendance": 79,
      "members": 147,
      "newFY": 122,
      "stillIn": 139,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2731,
      "name": "Baselios Mathews II College of Engineering, Sasthamcotta",
      "district": "kollam",
      "events": 10,
      "types": {
        "Core_Team_Meeting": 3,
        "Meetup": 4,
        "Workshop": 3
      },
      "uniqueAttendees": 108,
      "returning": 29,
      "totalAttendance": 163,
      "members": 210,
      "newFY": 174,
      "stillIn": 202,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 6
    },
    {
      "id": 2691,
      "name": "Carmel College of Engineering and Technology, Punnapra",
      "district": "alappuzha",
      "events": 4,
      "types": {
        "Talk_Session": 2,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 30,
      "returning": 3,
      "totalAttendance": 33,
      "members": 90,
      "newFY": 67,
      "stillIn": 76,
      "alumni": 14,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2426,
      "name": "Christ College of Engineering, Irinjalakuda",
      "district": "thrissur",
      "events": 10,
      "types": {
        "Meetup": 4,
        "Bootcamp": 1,
        "Learning_Program": 5
      },
      "uniqueAttendees": 216,
      "returning": 53,
      "totalAttendance": 320,
      "members": 589,
      "newFY": 122,
      "stillIn": 569,
      "alumni": 20,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2907,
      "name": "Cochin University College of Engineering, Kuttanad",
      "district": "alappuzha",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 776,
      "newFY": 14,
      "stillIn": 692,
      "alumni": 79,
      "gradUnknown": 5,
      "projects": 11
    },
    {
      "id": 2606,
      "name": "College of Engineering, Adoor",
      "district": "pathanamthitta",
      "events": 5,
      "types": {
        "Core_Team_Meeting": 2,
        "Learning_Program": 2,
        "Meetup": 1
      },
      "uniqueAttendees": 29,
      "returning": 10,
      "totalAttendance": 49,
      "members": 204,
      "newFY": 23,
      "stillIn": 178,
      "alumni": 26,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2433,
      "name": "College of Engineering, Alappuzha",
      "district": "alappuzha",
      "events": 11,
      "types": {
        "Core_Team_Meeting": 1,
        "Talk_Session": 1,
        "Workshop": 2,
        "Meetup": 7
      },
      "uniqueAttendees": 126,
      "returning": 37,
      "totalAttendance": 233,
      "members": 480,
      "newFY": 34,
      "stillIn": 462,
      "alumni": 18,
      "gradUnknown": 0,
      "projects": 5
    },
    {
      "id": 2616,
      "name": "College of Engineering, Attingal",
      "district": "thiruvananthapuram",
      "events": 8,
      "types": {
        "Core_Team_Meeting": 4,
        "Talk_Session": 2,
        "Workshop": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 66,
      "returning": 25,
      "totalAttendance": 119,
      "members": 355,
      "newFY": 75,
      "stillIn": 342,
      "alumni": 12,
      "gradUnknown": 1,
      "projects": 2
    },
    {
      "id": 2608,
      "name": "College of Engineering, Chengannur",
      "district": "alappuzha",
      "events": 6,
      "types": {
        "Meetup": 3,
        "Talk_Session": 3
      },
      "uniqueAttendees": 68,
      "returning": 15,
      "totalAttendance": 90,
      "members": 734,
      "newFY": 28,
      "stillIn": 660,
      "alumni": 73,
      "gradUnknown": 1,
      "projects": 2
    },
    {
      "id": 2609,
      "name": "College of Engineering, Kallooppara",
      "district": "pathanamthitta",
      "events": 3,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 66,
      "returning": 1,
      "totalAttendance": 67,
      "members": 371,
      "newFY": 26,
      "stillIn": 360,
      "alumni": 11,
      "gradUnknown": 0,
      "projects": 2
    },
    {
      "id": 2607,
      "name": "College of Engineering, Karunagappally",
      "district": "kollam",
      "events": 8,
      "types": {
        "Talk_Session": 2,
        "Core_Team_Meeting": 1,
        "Meetup": 2,
        "Learning_Program": 3
      },
      "uniqueAttendees": 44,
      "returning": 22,
      "totalAttendance": 99,
      "members": 381,
      "newFY": 7,
      "stillIn": 355,
      "alumni": 24,
      "gradUnknown": 2,
      "projects": 6
    },
    {
      "id": 2602,
      "name": "College of Engineering, Munnar",
      "district": "idukki",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 17,
      "returning": 0,
      "totalAttendance": 17,
      "members": 375,
      "newFY": 56,
      "stillIn": 355,
      "alumni": 19,
      "gradUnknown": 1,
      "projects": 0
    },
    {
      "id": 2610,
      "name": "College of Engineering, Perumon",
      "district": "kollam",
      "events": 11,
      "types": {
        "Talk_Session": 1,
        "Core_Team_Meeting": 1,
        "Meetup": 4,
        "Learning_Program": 2,
        "Workshop": 3
      },
      "uniqueAttendees": 119,
      "returning": 24,
      "totalAttendance": 170,
      "members": 525,
      "newFY": 55,
      "stillIn": 485,
      "alumni": 40,
      "gradUnknown": 0,
      "projects": 3
    },
    {
      "id": 2612,
      "name": "College of Engineering, Poonjar",
      "district": "kottayam",
      "events": 4,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1,
        "Learning_Program": 2
      },
      "uniqueAttendees": 41,
      "returning": 33,
      "totalAttendance": 75,
      "members": 177,
      "newFY": 1,
      "stillIn": 172,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2355,
      "name": "College of Engineering, Thiruvananthapuram",
      "district": "thiruvananthapuram",
      "events": 11,
      "types": {
        "Learning_Program": 7,
        "Workshop": 1,
        "Meetup": 1,
        "Core_Team_Meeting": 1,
        "Talk_Session": 1
      },
      "uniqueAttendees": 75,
      "returning": 38,
      "totalAttendance": 168,
      "members": 784,
      "newFY": 37,
      "stillIn": 694,
      "alumni": 87,
      "gradUnknown": 3,
      "projects": 0
    },
    {
      "id": 2613,
      "name": "College of Engineering, Trikaripur",
      "district": "kasaragod",
      "events": 13,
      "types": {
        "Learning_Program": 5,
        "Meetup": 5,
        "Core_Team_Meeting": 2,
        "Talk_Session": 1
      },
      "uniqueAttendees": 62,
      "returning": 21,
      "totalAttendance": 113,
      "members": 200,
      "newFY": 31,
      "stillIn": 185,
      "alumni": 15,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2618,
      "name": "College of Engineering, Vadakara",
      "district": "kozhikode",
      "events": 7,
      "types": {
        "Workshop": 2,
        "Talk_Session": 2,
        "Meetup": 3
      },
      "uniqueAttendees": 87,
      "returning": 41,
      "totalAttendance": 134,
      "members": 452,
      "newFY": 11,
      "stillIn": 423,
      "alumni": 27,
      "gradUnknown": 2,
      "projects": 3
    },
    {
      "id": 2938,
      "name": "Duxford College for Advanced Studies",
      "district": "malappuram",
      "events": 4,
      "types": {
        "Core_Team_Meeting": 2,
        "Meetup": 2
      },
      "uniqueAttendees": 21,
      "returning": 9,
      "totalAttendance": 36,
      "members": 58,
      "newFY": 55,
      "stillIn": 57,
      "alumni": 1,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1810,
      "name": "EMEA College of Arts & Science , Kondotty",
      "district": "malappuram",
      "events": 2,
      "types": {
        "Bootcamp": 1,
        "Workshop": 1
      },
      "uniqueAttendees": 16,
      "returning": 0,
      "totalAttendance": 16,
      "members": 255,
      "newFY": 26,
      "stillIn": 224,
      "alumni": 31,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1708,
      "name": "Farook College, Farook",
      "district": "kozhikode",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 2,
        "Meetup": 1
      },
      "uniqueAttendees": 110,
      "returning": 2,
      "totalAttendance": 112,
      "members": 606,
      "newFY": 116,
      "stillIn": 538,
      "alumni": 66,
      "gradUnknown": 2,
      "projects": 3
    },
    {
      "id": 2073,
      "name": "Federal Institute of Science & Technology (FISAT), Angamaly",
      "district": "ernakulam",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 23,
      "returning": 0,
      "totalAttendance": 23,
      "members": 163,
      "newFY": 48,
      "stillIn": 96,
      "alumni": 67,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 1664,
      "name": "Government Engineering College, Thrissur",
      "district": "thrissur",
      "events": 9,
      "types": {
        "Hackathon": 1,
        "Meetup": 3,
        "Learning_Program": 5
      },
      "uniqueAttendees": 133,
      "returning": 39,
      "totalAttendance": 184,
      "members": 960,
      "newFY": 60,
      "stillIn": 897,
      "alumni": 60,
      "gradUnknown": 3,
      "projects": 11
    },
    {
      "id": 1755,
      "name": "Government Engineering College, West Hill",
      "district": "kozhikode",
      "events": 4,
      "types": {
        "Talk_Session": 1,
        "Core_Team_Meeting": 2,
        "Meetup": 1
      },
      "uniqueAttendees": 41,
      "returning": 15,
      "totalAttendance": 69,
      "members": 382,
      "newFY": 18,
      "stillIn": 359,
      "alumni": 21,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 2917,
      "name": "ICCS College of Engineering and Management",
      "district": "thrissur",
      "events": 3,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 83,
      "returning": 3,
      "totalAttendance": 87,
      "members": 147,
      "newFY": 12,
      "stillIn": 139,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2074,
      "name": "Ilahia College of Engineering and Technology, Mulavoor",
      "district": "ernakulam",
      "events": 6,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 3,
        "Workshop": 2
      },
      "uniqueAttendees": 97,
      "returning": 11,
      "totalAttendance": 111,
      "members": 359,
      "newFY": 51,
      "stillIn": 317,
      "alumni": 42,
      "gradUnknown": 0,
      "projects": 3
    },
    {
      "id": 2924,
      "name": "Indian Institute of Information Technology (IIIT), Kottayam",
      "district": "kottayam",
      "events": 1,
      "types": {
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 4,
      "returning": 0,
      "totalAttendance": 4,
      "members": 34,
      "newFY": 17,
      "stillIn": 32,
      "alumni": 2,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2688,
      "name": "Institute of Engineering and Technology, Thenhipalam",
      "district": "malappuram",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Learning_Program": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 70,
      "returning": 2,
      "totalAttendance": 72,
      "members": 164,
      "newFY": 141,
      "stillIn": 149,
      "alumni": 15,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2076,
      "name": "Jai Bharath College of Management & Engineering Technology, Arackappady",
      "district": "ernakulam",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 33,
      "newFY": 12,
      "stillIn": 25,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2928,
      "name": "Jain University",
      "district": "ernakulam",
      "events": 2,
      "types": {
        "Core_Team_Meeting": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 86,
      "returning": 1,
      "totalAttendance": 87,
      "members": 269,
      "newFY": 190,
      "stillIn": 262,
      "alumni": 5,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 1899,
      "name": "Jawaharlal College of Engineering and Technology, Lakkidi",
      "district": "palakkad",
      "events": 6,
      "types": {
        "Talk_Session": 2,
        "Meetup": 1,
        "Learning_Program": 2,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 376,
      "returning": 40,
      "totalAttendance": 451,
      "members": 416,
      "newFY": 400,
      "stillIn": 407,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 1677,
      "name": "Jyothi Engineering College, Cheruthuruthy",
      "district": "thrissur",
      "events": 8,
      "types": {
        "Learning_Program": 3,
        "Talk_Session": 2,
        "Meetup": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 117,
      "returning": 51,
      "totalAttendance": 199,
      "members": 892,
      "newFY": 81,
      "stillIn": 812,
      "alumni": 79,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2077,
      "name": "KMEA Engineering College, Edathala",
      "district": "ernakulam",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 11,
      "returning": 0,
      "totalAttendance": 11,
      "members": 182,
      "newFY": 17,
      "stillIn": 143,
      "alumni": 38,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2270,
      "name": "LBS College of Engineering, Povval",
      "district": "kasaragod",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 41,
      "returning": 0,
      "totalAttendance": 41,
      "members": 622,
      "newFY": 18,
      "stillIn": 586,
      "alumni": 33,
      "gradUnknown": 3,
      "projects": 0
    },
    {
      "id": 2421,
      "name": "LBS Institute of Technology for Women, Poojappura",
      "district": "thiruvananthapuram",
      "events": 12,
      "types": {
        "Meetup": 2,
        "Talk_Session": 1,
        "Learning_Program": 6,
        "Core_Team_Meeting": 2,
        "Hackathon": 1
      },
      "uniqueAttendees": 309,
      "returning": 94,
      "totalAttendance": 471,
      "members": 1125,
      "newFY": 178,
      "stillIn": 1090,
      "alumni": 32,
      "gradUnknown": 3,
      "projects": 1
    },
    {
      "id": 2427,
      "name": "Lourdes Matha College of Science & Technology, Kutttichal",
      "district": "thiruvananthapuram",
      "events": 9,
      "types": {
        "Core_Team_Meeting": 4,
        "Meetup": 2,
        "Learning_Program": 3
      },
      "uniqueAttendees": 68,
      "returning": 41,
      "totalAttendance": 132,
      "members": 117,
      "newFY": 49,
      "stillIn": 112,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1799,
      "name": "Majlis Arts & Science College, Valanchery",
      "district": "malappuram",
      "events": 2,
      "types": {
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 3,
      "returning": 1,
      "totalAttendance": 4,
      "members": 134,
      "newFY": 4,
      "stillIn": 119,
      "alumni": 15,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2068,
      "name": "Mar Athanasius College of Engineering, Kothamangalam",
      "district": "ernakulam",
      "events": 3,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 79,
      "returning": 3,
      "totalAttendance": 82,
      "members": 770,
      "newFY": 61,
      "stillIn": 720,
      "alumni": 49,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 1949,
      "name": "Mar Baselios Christian College of Engineering and Technology, Peerumedu",
      "district": "idukki",
      "events": 3,
      "types": {
        "Meetup": 1,
        "Talk_Session": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 25,
      "returning": 2,
      "totalAttendance": 27,
      "members": 470,
      "newFY": 3,
      "stillIn": 438,
      "alumni": 32,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2702,
      "name": "MES College of Engineering and Technology, Kunnukara",
      "district": "ernakulam",
      "events": 2,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 41,
      "returning": 4,
      "totalAttendance": 45,
      "members": 224,
      "newFY": 18,
      "stillIn": 214,
      "alumni": 10,
      "gradUnknown": 0,
      "projects": 7
    },
    {
      "id": 2635,
      "name": "Model Engineering College, Thrikkakara",
      "district": "ernakulam",
      "events": 17,
      "types": {
        "Talk_Session": 1,
        "Learning_Program": 10,
        "Core_Team_Meeting": 6
      },
      "uniqueAttendees": 175,
      "returning": 105,
      "totalAttendance": 521,
      "members": 1750,
      "newFY": 109,
      "stillIn": 1559,
      "alumni": 187,
      "gradUnknown": 4,
      "projects": 20
    },
    {
      "id": 1710,
      "name": "Muhammed Abdurahiman Memorial Orphanage College, Mukkam",
      "district": "kozhikode",
      "events": 4,
      "types": {
        "Meetup": 3,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 100,
      "returning": 13,
      "totalAttendance": 115,
      "members": 191,
      "newFY": 49,
      "stillIn": 175,
      "alumni": 15,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2704,
      "name": "Muthoot Institute of Technology & Science (MITS), Puthencruz",
      "district": "ernakulam",
      "events": 6,
      "types": {
        "Learning_Program": 2,
        "Core_Team_Meeting": 2,
        "Meetup": 1,
        "Workshop": 1
      },
      "uniqueAttendees": 130,
      "returning": 28,
      "totalAttendance": 176,
      "members": 1096,
      "newFY": 63,
      "stillIn": 1002,
      "alumni": 92,
      "gradUnknown": 2,
      "projects": 7
    },
    {
      "id": 1895,
      "name": "NSS College of Engineering, Akathethara",
      "district": "palakkad",
      "events": 5,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 1,
        "Workshop": 2
      },
      "uniqueAttendees": 83,
      "returning": 33,
      "totalAttendance": 124,
      "members": 641,
      "newFY": 73,
      "stillIn": 597,
      "alumni": 43,
      "gradUnknown": 1,
      "projects": 4
    },
    {
      "id": 2821,
      "name": "Paramekkavu College of Arts & Science, Punkunnam",
      "district": "thrissur",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 7,
      "newFY": 0,
      "stillIn": 2,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2735,
      "name": "Providence College of Engineering, Chengannur",
      "district": "alappuzha",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 41,
      "newFY": 9,
      "stillIn": 35,
      "alumni": 6,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2160,
      "name": "Rajiv Gandhi Institute of Technology, Velloor",
      "district": "kottayam",
      "events": 8,
      "types": {
        "Core_Team_Meeting": 2,
        "Talk_Session": 2,
        "Meetup": 2,
        "Learning_Program": 2
      },
      "uniqueAttendees": 117,
      "returning": 30,
      "totalAttendance": 171,
      "members": 558,
      "newFY": 48,
      "stillIn": 491,
      "alumni": 66,
      "gradUnknown": 1,
      "projects": 5
    },
    {
      "id": 2534,
      "name": "Sahrdaya College of Advanced Studies, Kodakara",
      "district": "thrissur",
      "events": 2,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 86,
      "returning": 0,
      "totalAttendance": 86,
      "members": 259,
      "newFY": 73,
      "stillIn": 239,
      "alumni": 20,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1676,
      "name": "Sahrdaya College of Engineering & Technology, Kodakara",
      "district": "thrissur",
      "events": 12,
      "types": {
        "Talk_Session": 1,
        "Learning_Program": 9,
        "Core_Team_Meeting": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 33,
      "returning": 19,
      "totalAttendance": 96,
      "members": 972,
      "newFY": 297,
      "stillIn": 906,
      "alumni": 64,
      "gradUnknown": 2,
      "projects": 0
    },
    {
      "id": 2148,
      "name": "Saintgits College of Applied Sciences, Pathamuttam",
      "district": "kottayam",
      "events": 5,
      "types": {
        "Learning_Program": 2,
        "Hackathon": 3
      },
      "uniqueAttendees": 82,
      "returning": 59,
      "totalAttendance": 153,
      "members": 104,
      "newFY": 97,
      "stillIn": 100,
      "alumni": 4,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2164,
      "name": "Saintgits College of Engineering, Pathamuttom",
      "district": "kottayam",
      "events": 2,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 19,
      "returning": 7,
      "totalAttendance": 26,
      "members": 646,
      "newFY": 16,
      "stillIn": 580,
      "alumni": 66,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2908,
      "name": "School of Engineering CUSAT, Kalamassery",
      "district": "ernakulam",
      "events": 6,
      "types": {
        "Workshop": 1,
        "Talk_Session": 2,
        "Learning_Program": 3
      },
      "uniqueAttendees": 121,
      "returning": 41,
      "totalAttendance": 186,
      "members": 2355,
      "newFY": 105,
      "stillIn": 1915,
      "alumni": 438,
      "gradUnknown": 2,
      "projects": 33
    },
    {
      "id": 2081,
      "name": "SCMS School of Engineering & Technology, Karukutty",
      "district": "ernakulam",
      "events": 5,
      "types": {
        "Learning_Program": 1,
        "Meetup": 1,
        "Core_Team_Meeting": 3
      },
      "uniqueAttendees": 62,
      "returning": 8,
      "totalAttendance": 74,
      "members": 1177,
      "newFY": 125,
      "stillIn": 1110,
      "alumni": 66,
      "gradUnknown": 1,
      "projects": 6
    },
    {
      "id": 2084,
      "name": "SNM Institute of Management & Technology, Maliankara",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Core_Team_Meeting": 4,
        "Meetup": 3
      },
      "uniqueAttendees": 117,
      "returning": 23,
      "totalAttendance": 155,
      "members": 450,
      "newFY": 35,
      "stillIn": 422,
      "alumni": 24,
      "gradUnknown": 4,
      "projects": 2
    },
    {
      "id": 2423,
      "name": "Sree Buddha College of Engineering, Pattoor",
      "district": "alappuzha",
      "events": 14,
      "types": {
        "Talk_Session": 1,
        "Meetup": 3,
        "Learning_Program": 7,
        "Core_Team_Meeting": 3
      },
      "uniqueAttendees": 112,
      "returning": 65,
      "totalAttendance": 257,
      "members": 320,
      "newFY": 106,
      "stillIn": 307,
      "alumni": 13,
      "gradUnknown": 0,
      "projects": 2
    },
    {
      "id": 2419,
      "name": "Sree Chitra Thirunal College of Engineering, Pappanamcode",
      "district": "thiruvananthapuram",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 37,
      "returning": 0,
      "totalAttendance": 37,
      "members": 501,
      "newFY": 11,
      "stillIn": 466,
      "alumni": 34,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2216,
      "name": "Sree Narayana Guru College of Engineering & Technology, Chalakode",
      "district": "kannur",
      "events": 6,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 2,
        "Talk_Session": 2
      },
      "uniqueAttendees": 206,
      "returning": 20,
      "totalAttendance": 248,
      "members": 307,
      "newFY": 265,
      "stillIn": 302,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2083,
      "name": "Sree Narayana Gurukulam College of Engineering, Kadayiruppu",
      "district": "ernakulam",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 127,
      "returning": 0,
      "totalAttendance": 127,
      "members": 363,
      "newFY": 112,
      "stillIn": 334,
      "alumni": 29,
      "gradUnknown": 0,
      "projects": 2
    },
    {
      "id": 2914,
      "name": "St. Joseph's College Devagiri",
      "district": "kozhikode",
      "events": 1,
      "types": {
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 322,
      "newFY": 11,
      "stillIn": 265,
      "alumni": 52,
      "gradUnknown": 5,
      "projects": 0
    },
    {
      "id": 2165,
      "name": "St. Josephs College of Engineering and Technology, Choondacherry",
      "district": "kottayam",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 309,
      "newFY": 28,
      "stillIn": 275,
      "alumni": 32,
      "gradUnknown": 2,
      "projects": 0
    },
    {
      "id": 1959,
      "name": "St.Thomas College, Ranni",
      "district": "pathanamthitta",
      "events": 1,
      "types": {
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 3,
      "returning": 0,
      "totalAttendance": 3,
      "members": 19,
      "newFY": 7,
      "stillIn": 18,
      "alumni": 1,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1673,
      "name": "Thejus College Engineering College, Erumapetti",
      "district": "thrissur",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Talk_Session": 2
      },
      "uniqueAttendees": 75,
      "returning": 0,
      "totalAttendance": 75,
      "members": 201,
      "newFY": 5,
      "stillIn": 188,
      "alumni": 13,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2357,
      "name": "TKM College of Engineering, Karicode",
      "district": "kollam",
      "events": 5,
      "types": {
        "Meetup": 1,
        "Talk_Session": 1,
        "Core_Team_Meeting": 3
      },
      "uniqueAttendees": 62,
      "returning": 7,
      "totalAttendance": 77,
      "members": 852,
      "newFY": 51,
      "stillIn": 791,
      "alumni": 59,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 2614,
      "name": "Toc H Institute of Science & Technology, Arakkunnam",
      "district": "ernakulam",
      "events": 4,
      "types": {
        "Core_Team_Meeting": 2,
        "Meetup": 2
      },
      "uniqueAttendees": 53,
      "returning": 17,
      "totalAttendance": 74,
      "members": 862,
      "newFY": 102,
      "stillIn": 810,
      "alumni": 50,
      "gradUnknown": 2,
      "projects": 7
    },
    {
      "id": 1797,
      "name": "Unity Women's College, Manjeri",
      "district": "malappuram",
      "events": 5,
      "types": {
        "Core_Team_Meeting": 1,
        "Learning_Program": 1,
        "Meetup": 2,
        "Talk_Session": 1
      },
      "uniqueAttendees": 92,
      "returning": 22,
      "totalAttendance": 119,
      "members": 174,
      "newFY": 64,
      "stillIn": 165,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1670,
      "name": "Vidya Academy of Science & Technology, Thalakkottukara",
      "district": "thrissur",
      "events": 8,
      "types": {
        "Talk_Session": 1,
        "Learning_Program": 7
      },
      "uniqueAttendees": 267,
      "returning": 76,
      "totalAttendance": 369,
      "members": 577,
      "newFY": 222,
      "stillIn": 534,
      "alumni": 42,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2217,
      "name": "Vimal Jyothi Engineering College, Chemperi",
      "district": "kannur",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Meetup": 1,
        "Hackathon": 1
      },
      "uniqueAttendees": 78,
      "returning": 10,
      "totalAttendance": 88,
      "members": 172,
      "newFY": 117,
      "stillIn": 153,
      "alumni": 19,
      "gradUnknown": 0,
      "projects": 29
    },
    {
      "id": 2085,
      "name": "Viswajyothi College of Engineering and Technology, Vazhakulam",
      "district": "ernakulam",
      "events": 4,
      "types": {
        "Core_Team_Meeting": 2,
        "Meetup": 2
      },
      "uniqueAttendees": 5,
      "returning": 3,
      "totalAttendance": 8,
      "members": 746,
      "newFY": 6,
      "stillIn": 624,
      "alumni": 121,
      "gradUnknown": 1,
      "projects": 3
    }
  ]
};
