// Auto-generated by .github/workflows/campus-update.yml
// Do NOT hand-edit -- this file is overwritten on each run.
window.CAMPUS_DATA = {
  "generatedAt": "2026-09-08",
  "generatedAtIso": "2026-09-08T08:38:26.934251+00:00",
  "windowSinceDate": "2026-04-01",
  "windowUntilDate": "2026-09-08",
  "campuses": [
    {
      "id": 2637,
      "name": "ACE College of Engineering, Karinkadamugal",
      "district": "thiruvananthapuram",
      "events": 2,
      "types": {
        "Learning_Program": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 4,
      "returning": 0,
      "totalAttendance": 4,
      "members": 63,
      "newFY": 35,
      "stillIn": 60,
      "alumni": 2,
      "gradUnknown": 1,
      "projects": 3
    },
    {
      "id": 2069,
      "name": "Adi Shankara Institute of Engineering and Technology, Mattoor",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 6
      },
      "uniqueAttendees": 27,
      "returning": 6,
      "totalAttendance": 51,
      "members": 787,
      "newFY": 133,
      "stillIn": 728,
      "alumni": 57,
      "gradUnknown": 2,
      "projects": 10
    },
    {
      "id": 2689,
      "name": "Ahalia School of Engineering & Technology, palakkad",
      "district": "palakkad",
      "events": 3,
      "types": {
        "Learning_Program": 1,
        "Meetup": 2
      },
      "uniqueAttendees": 38,
      "returning": 9,
      "totalAttendance": 50,
      "members": 126,
      "newFY": 67,
      "stillIn": 119,
      "alumni": 7,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1948,
      "name": "Al Azhar College of Engineering & Technology, Perumpillichira",
      "district": "idukki",
      "events": 4,
      "types": {
        "Talk_Session": 2,
        "Meetup": 2
      },
      "uniqueAttendees": 6,
      "returning": 0,
      "totalAttendance": 6,
      "members": 46,
      "newFY": 37,
      "stillIn": 37,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2070,
      "name": "Albertian Institute of Science and Technology (AISAT), Kalamassery",
      "district": "ernakulam",
      "events": 3,
      "types": {
        "Bootcamp": 1,
        "Meetup": 1,
        "Learning_Program": 1
      },
      "uniqueAttendees": 216,
      "returning": 14,
      "totalAttendance": 231,
      "members": 775,
      "newFY": 206,
      "stillIn": 705,
      "alumni": 67,
      "gradUnknown": 3,
      "projects": 25
    },
    {
      "id": 1651,
      "name": "Ansar Women's College, Perumpilavu",
      "district": "thrissur",
      "events": 4,
      "types": {
        "Core_Team_Meeting": 1,
        "Meetup": 2,
        "Learning_Program": 1
      },
      "uniqueAttendees": 72,
      "returning": 7,
      "totalAttendance": 79,
      "members": 164,
      "newFY": 139,
      "stillIn": 156,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2731,
      "name": "Baselios Mathews II College of Engineering, Sasthamcotta",
      "district": "kollam",
      "events": 13,
      "types": {
        "Core_Team_Meeting": 4,
        "Meetup": 6,
        "Workshop": 3
      },
      "uniqueAttendees": 109,
      "returning": 31,
      "totalAttendance": 175,
      "members": 213,
      "newFY": 177,
      "stillIn": 205,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 6
    },
    {
      "id": 2691,
      "name": "Carmel College of Engineering and Technology, Punnapra",
      "district": "alappuzha",
      "events": 4,
      "types": {
        "Talk_Session": 2,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 30,
      "returning": 3,
      "totalAttendance": 33,
      "members": 197,
      "newFY": 174,
      "stillIn": 183,
      "alumni": 14,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2426,
      "name": "Christ College of Engineering, Irinjalakuda",
      "district": "thrissur",
      "events": 13,
      "types": {
        "Meetup": 5,
        "Bootcamp": 1,
        "Workshop": 1,
        "Hackathon": 1,
        "Learning_Program": 5
      },
      "uniqueAttendees": 280,
      "returning": 116,
      "totalAttendance": 488,
      "members": 710,
      "newFY": 241,
      "stillIn": 690,
      "alumni": 20,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2907,
      "name": "Cochin University College of Engineering, Kuttanad",
      "district": "alappuzha",
      "events": 1,
      "types": {
        "Learning_Program": 1
      },
      "uniqueAttendees": 78,
      "returning": 0,
      "totalAttendance": 78,
      "members": 780,
      "newFY": 18,
      "stillIn": 696,
      "alumni": 79,
      "gradUnknown": 5,
      "projects": 14
    },
    {
      "id": 2606,
      "name": "College of Engineering, Adoor",
      "district": "pathanamthitta",
      "events": 6,
      "types": {
        "Learning_Program": 2,
        "Core_Team_Meeting": 3,
        "Meetup": 1
      },
      "uniqueAttendees": 29,
      "returning": 10,
      "totalAttendance": 55,
      "members": 210,
      "newFY": 29,
      "stillIn": 184,
      "alumni": 26,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2433,
      "name": "College of Engineering, Alappuzha",
      "district": "alappuzha",
      "events": 17,
      "types": {
        "Talk_Session": 2,
        "Workshop": 2,
        "Learning_Program": 3,
        "Core_Team_Meeting": 2,
        "Meetup": 8
      },
      "uniqueAttendees": 236,
      "returning": 99,
      "totalAttendance": 469,
      "members": 605,
      "newFY": 159,
      "stillIn": 587,
      "alumni": 18,
      "gradUnknown": 0,
      "projects": 7
    },
    {
      "id": 2616,
      "name": "College of Engineering, Attingal",
      "district": "thiruvananthapuram",
      "events": 10,
      "types": {
        "Talk_Session": 3,
        "Meetup": 1,
        "Learning_Program": 1,
        "Core_Team_Meeting": 4,
        "Workshop": 1
      },
      "uniqueAttendees": 88,
      "returning": 31,
      "totalAttendance": 165,
      "members": 377,
      "newFY": 97,
      "stillIn": 364,
      "alumni": 12,
      "gradUnknown": 1,
      "projects": 8
    },
    {
      "id": 2608,
      "name": "College of Engineering, Chengannur",
      "district": "alappuzha",
      "events": 7,
      "types": {
        "Learning_Program": 1,
        "Meetup": 3,
        "Talk_Session": 3
      },
      "uniqueAttendees": 98,
      "returning": 16,
      "totalAttendance": 123,
      "members": 752,
      "newFY": 46,
      "stillIn": 677,
      "alumni": 74,
      "gradUnknown": 1,
      "projects": 2
    },
    {
      "id": 2609,
      "name": "College of Engineering, Kallooppara",
      "district": "pathanamthitta",
      "events": 7,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 2,
        "Learning_Program": 4
      },
      "uniqueAttendees": 99,
      "returning": 27,
      "totalAttendance": 154,
      "members": 398,
      "newFY": 53,
      "stillIn": 386,
      "alumni": 12,
      "gradUnknown": 0,
      "projects": 12
    },
    {
      "id": 2607,
      "name": "College of Engineering, Karunagappally",
      "district": "kollam",
      "events": 11,
      "types": {
        "Core_Team_Meeting": 1,
        "Hackathon": 1,
        "Learning_Program": 4,
        "Talk_Session": 3,
        "Meetup": 2
      },
      "uniqueAttendees": 95,
      "returning": 25,
      "totalAttendance": 174,
      "members": 446,
      "newFY": 70,
      "stillIn": 419,
      "alumni": 24,
      "gradUnknown": 3,
      "projects": 13
    },
    {
      "id": 2602,
      "name": "College of Engineering, Munnar",
      "district": "idukki",
      "events": 4,
      "types": {
        "Talk_Session": 1,
        "Workshop": 1,
        "Meetup": 2
      },
      "uniqueAttendees": 120,
      "returning": 29,
      "totalAttendance": 151,
      "members": 431,
      "newFY": 112,
      "stillIn": 411,
      "alumni": 19,
      "gradUnknown": 1,
      "projects": 1
    },
    {
      "id": 2610,
      "name": "College of Engineering, Perumon",
      "district": "kollam",
      "events": 15,
      "types": {
        "Meetup": 4,
        "Talk_Session": 2,
        "Core_Team_Meeting": 2,
        "Learning_Program": 4,
        "Workshop": 3
      },
      "uniqueAttendees": 215,
      "returning": 41,
      "totalAttendance": 295,
      "members": 644,
      "newFY": 174,
      "stillIn": 604,
      "alumni": 40,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2612,
      "name": "College of Engineering, Poonjar",
      "district": "kottayam",
      "events": 5,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1,
        "Learning_Program": 3
      },
      "uniqueAttendees": 56,
      "returning": 34,
      "totalAttendance": 94,
      "members": 210,
      "newFY": 34,
      "stillIn": 205,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 3
    },
    {
      "id": 2355,
      "name": "College of Engineering, Thiruvananthapuram",
      "district": "thiruvananthapuram",
      "events": 13,
      "types": {
        "Workshop": 1,
        "Meetup": 1,
        "Core_Team_Meeting": 1,
        "Learning_Program": 9,
        "Talk_Session": 1
      },
      "uniqueAttendees": 131,
      "returning": 52,
      "totalAttendance": 251,
      "members": 867,
      "newFY": 118,
      "stillIn": 774,
      "alumni": 90,
      "gradUnknown": 3,
      "projects": 0
    },
    {
      "id": 2613,
      "name": "College of Engineering, Trikaripur",
      "district": "kasaragod",
      "events": 15,
      "types": {
        "Hackathon": 1,
        "Learning_Program": 5,
        "Meetup": 5,
        "Core_Team_Meeting": 2,
        "Talk_Session": 2
      },
      "uniqueAttendees": 68,
      "returning": 22,
      "totalAttendance": 122,
      "members": 227,
      "newFY": 58,
      "stillIn": 212,
      "alumni": 15,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2618,
      "name": "College of Engineering, Vadakara",
      "district": "kozhikode",
      "events": 8,
      "types": {
        "Workshop": 2,
        "Talk_Session": 2,
        "Meetup": 2,
        "Learning_Program": 2
      },
      "uniqueAttendees": 95,
      "returning": 43,
      "totalAttendance": 157,
      "members": 498,
      "newFY": 57,
      "stillIn": 468,
      "alumni": 28,
      "gradUnknown": 2,
      "projects": 6
    },
    {
      "id": 2938,
      "name": "Duxford College for Advanced Studies",
      "district": "malappuram",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 2,
        "Meetup": 1
      },
      "uniqueAttendees": 21,
      "returning": 8,
      "totalAttendance": 30,
      "members": 58,
      "newFY": 55,
      "stillIn": 57,
      "alumni": 1,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1810,
      "name": "EMEA College of Arts & Science , Kondotty",
      "district": "malappuram",
      "events": 4,
      "types": {
        "Learning_Program": 2,
        "Workshop": 1,
        "Bootcamp": 1
      },
      "uniqueAttendees": 37,
      "returning": 4,
      "totalAttendance": 41,
      "members": 274,
      "newFY": 46,
      "stillIn": 244,
      "alumni": 30,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 1708,
      "name": "Farook College, Farook",
      "district": "kozhikode",
      "events": 4,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 125,
      "returning": 17,
      "totalAttendance": 142,
      "members": 618,
      "newFY": 128,
      "stillIn": 548,
      "alumni": 68,
      "gradUnknown": 2,
      "projects": 3
    },
    {
      "id": 2073,
      "name": "Federal Institute of Science & Technology (FISAT), Angamaly",
      "district": "ernakulam",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 23,
      "returning": 0,
      "totalAttendance": 23,
      "members": 229,
      "newFY": 114,
      "stillIn": 162,
      "alumni": 67,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 1664,
      "name": "Government Engineering College, Thrissur",
      "district": "thrissur",
      "events": 13,
      "types": {
        "Hackathon": 1,
        "Core_Team_Meeting": 3,
        "Meetup": 4,
        "Learning_Program": 5
      },
      "uniqueAttendees": 228,
      "returning": 45,
      "totalAttendance": 312,
      "members": 1122,
      "newFY": 222,
      "stillIn": 1059,
      "alumni": 60,
      "gradUnknown": 3,
      "projects": 16
    },
    {
      "id": 1755,
      "name": "Government Engineering College, West Hill",
      "district": "kozhikode",
      "events": 4,
      "types": {
        "Talk_Session": 1,
        "Meetup": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 41,
      "returning": 15,
      "totalAttendance": 69,
      "members": 391,
      "newFY": 27,
      "stillIn": 368,
      "alumni": 21,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 2917,
      "name": "ICCS College of Engineering and Management",
      "district": "thrissur",
      "events": 3,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 83,
      "returning": 4,
      "totalAttendance": 89,
      "members": 180,
      "newFY": 45,
      "stillIn": 171,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2074,
      "name": "Ilahia College of Engineering and Technology, Mulavoor",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 3,
        "Workshop": 3
      },
      "uniqueAttendees": 98,
      "returning": 14,
      "totalAttendance": 117,
      "members": 363,
      "newFY": 55,
      "stillIn": 321,
      "alumni": 42,
      "gradUnknown": 0,
      "projects": 3
    },
    {
      "id": 2924,
      "name": "Indian Institute of Information Technology (IIIT), Kottayam",
      "district": "kottayam",
      "events": 1,
      "types": {
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 4,
      "returning": 0,
      "totalAttendance": 4,
      "members": 37,
      "newFY": 20,
      "stillIn": 35,
      "alumni": 2,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2688,
      "name": "Institute of Engineering and Technology, Thenhipalam",
      "district": "malappuram",
      "events": 6,
      "types": {
        "Core_Team_Meeting": 1,
        "Learning_Program": 4,
        "Meetup": 1
      },
      "uniqueAttendees": 85,
      "returning": 15,
      "totalAttendance": 103,
      "members": 189,
      "newFY": 166,
      "stillIn": 173,
      "alumni": 16,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2076,
      "name": "Jai Bharath College of Management & Engineering Technology, Arackappady",
      "district": "ernakulam",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 33,
      "newFY": 12,
      "stillIn": 25,
      "alumni": 8,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2928,
      "name": "Jain University",
      "district": "ernakulam",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Learning_Program": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 102,
      "returning": 5,
      "totalAttendance": 107,
      "members": 295,
      "newFY": 216,
      "stillIn": 288,
      "alumni": 5,
      "gradUnknown": 2,
      "projects": 9
    },
    {
      "id": 1899,
      "name": "Jawaharlal College of Engineering and Technology, Lakkidi",
      "district": "palakkad",
      "events": 10,
      "types": {
        "Talk_Session": 2,
        "Learning_Program": 4,
        "Meetup": 2,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 385,
      "returning": 53,
      "totalAttendance": 524,
      "members": 460,
      "newFY": 444,
      "stillIn": 451,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 1677,
      "name": "Jyothi Engineering College, Cheruthuruthy",
      "district": "thrissur",
      "events": 16,
      "types": {
        "Learning_Program": 9,
        "Meetup": 1,
        "Core_Team_Meeting": 2,
        "Hackathon": 1,
        "Talk_Session": 3
      },
      "uniqueAttendees": 209,
      "returning": 89,
      "totalAttendance": 390,
      "members": 936,
      "newFY": 125,
      "stillIn": 854,
      "alumni": 81,
      "gradUnknown": 1,
      "projects": 18
    },
    {
      "id": 2077,
      "name": "KMEA Engineering College, Edathala",
      "district": "ernakulam",
      "events": 2,
      "types": {
        "Meetup": 1,
        "Bootcamp": 1
      },
      "uniqueAttendees": 11,
      "returning": 0,
      "totalAttendance": 11,
      "members": 193,
      "newFY": 28,
      "stillIn": 154,
      "alumni": 38,
      "gradUnknown": 1,
      "projects": 4
    },
    {
      "id": 2270,
      "name": "LBS College of Engineering, Povval",
      "district": "kasaragod",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 41,
      "returning": 0,
      "totalAttendance": 41,
      "members": 629,
      "newFY": 25,
      "stillIn": 592,
      "alumni": 34,
      "gradUnknown": 3,
      "projects": 0
    },
    {
      "id": 2421,
      "name": "LBS Institute of Technology for Women, Poojappura",
      "district": "thiruvananthapuram",
      "events": 22,
      "types": {
        "Meetup": 3,
        "Learning_Program": 13,
        "Talk_Session": 2,
        "Core_Team_Meeting": 3,
        "Hackathon": 1
      },
      "uniqueAttendees": 591,
      "returning": 298,
      "totalAttendance": 1302,
      "members": 1325,
      "newFY": 378,
      "stillIn": 1290,
      "alumni": 32,
      "gradUnknown": 3,
      "projects": 39
    },
    {
      "id": 2427,
      "name": "Lourdes Matha College of Science & Technology, Kutttichal",
      "district": "thiruvananthapuram",
      "events": 13,
      "types": {
        "Learning_Program": 4,
        "Core_Team_Meeting": 7,
        "Meetup": 2
      },
      "uniqueAttendees": 75,
      "returning": 43,
      "totalAttendance": 155,
      "members": 192,
      "newFY": 124,
      "stillIn": 186,
      "alumni": 6,
      "gradUnknown": 0,
      "projects": 11
    },
    {
      "id": 1799,
      "name": "Majlis Arts & Science College, Valanchery",
      "district": "malappuram",
      "events": 4,
      "types": {
        "Core_Team_Meeting": 2,
        "Learning_Program": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 3,
      "returning": 1,
      "totalAttendance": 4,
      "members": 137,
      "newFY": 7,
      "stillIn": 122,
      "alumni": 15,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2068,
      "name": "Mar Athanasius College of Engineering, Kothamangalam",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Meetup": 2,
        "Core_Team_Meeting": 4,
        "Learning_Program": 1
      },
      "uniqueAttendees": 140,
      "returning": 5,
      "totalAttendance": 149,
      "members": 881,
      "newFY": 170,
      "stillIn": 830,
      "alumni": 49,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 1949,
      "name": "Mar Baselios Christian College of Engineering and Technology, Peerumedu",
      "district": "idukki",
      "events": 3,
      "types": {
        "Meetup": 1,
        "Core_Team_Meeting": 1,
        "Talk_Session": 1
      },
      "uniqueAttendees": 25,
      "returning": 2,
      "totalAttendance": 27,
      "members": 470,
      "newFY": 3,
      "stillIn": 438,
      "alumni": 32,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2702,
      "name": "MES College of Engineering and Technology, Kunnukara",
      "district": "ernakulam",
      "events": 12,
      "types": {
        "Meetup": 2,
        "Learning_Program": 6,
        "Workshop": 2,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 166,
      "returning": 33,
      "totalAttendance": 232,
      "members": 369,
      "newFY": 158,
      "stillIn": 358,
      "alumni": 11,
      "gradUnknown": 0,
      "projects": 7
    },
    {
      "id": 2635,
      "name": "Model Engineering College, Thrikkakara",
      "district": "ernakulam",
      "events": 19,
      "types": {
        "Workshop": 2,
        "Core_Team_Meeting": 6,
        "Talk_Session": 1,
        "Learning_Program": 10
      },
      "uniqueAttendees": 210,
      "returning": 130,
      "totalAttendance": 625,
      "members": 1800,
      "newFY": 159,
      "stillIn": 1608,
      "alumni": 188,
      "gradUnknown": 4,
      "projects": 44
    },
    {
      "id": 1710,
      "name": "Muhammed Abdurahiman Memorial Orphanage College, Mukkam",
      "district": "kozhikode",
      "events": 4,
      "types": {
        "Meetup": 3,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 100,
      "returning": 13,
      "totalAttendance": 115,
      "members": 195,
      "newFY": 53,
      "stillIn": 177,
      "alumni": 17,
      "gradUnknown": 1,
      "projects": 5
    },
    {
      "id": 2704,
      "name": "Muthoot Institute of Technology & Science (MITS), Puthencruz",
      "district": "ernakulam",
      "events": 8,
      "types": {
        "Core_Team_Meeting": 2,
        "Workshop": 1,
        "Learning_Program": 4,
        "Meetup": 1
      },
      "uniqueAttendees": 257,
      "returning": 118,
      "totalAttendance": 442,
      "members": 1306,
      "newFY": 272,
      "stillIn": 1211,
      "alumni": 92,
      "gradUnknown": 3,
      "projects": 39
    },
    {
      "id": 1895,
      "name": "NSS College of Engineering, Akathethara",
      "district": "palakkad",
      "events": 7,
      "types": {
        "Learning_Program": 1,
        "Hackathon": 1,
        "Core_Team_Meeting": 1,
        "Meetup": 2,
        "Workshop": 2
      },
      "uniqueAttendees": 101,
      "returning": 37,
      "totalAttendance": 150,
      "members": 689,
      "newFY": 120,
      "stillIn": 642,
      "alumni": 45,
      "gradUnknown": 2,
      "projects": 9
    },
    {
      "id": 2821,
      "name": "Paramekkavu College of Arts & Science, Punkunnam",
      "district": "thrissur",
      "events": 0,
      "types": {},
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 7,
      "newFY": 0,
      "stillIn": 2,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 0
    },
    {
      "id": 2735,
      "name": "Providence College of Engineering, Chengannur",
      "district": "alappuzha",
      "events": 1,
      "types": {
        "Meetup": 1
      },
      "uniqueAttendees": 49,
      "returning": 0,
      "totalAttendance": 49,
      "members": 95,
      "newFY": 63,
      "stillIn": 89,
      "alumni": 6,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2160,
      "name": "Rajiv Gandhi Institute of Technology, Velloor",
      "district": "kottayam",
      "events": 12,
      "types": {
        "Workshop": 1,
        "Talk_Session": 2,
        "Core_Team_Meeting": 2,
        "Meetup": 2,
        "Learning_Program": 5
      },
      "uniqueAttendees": 253,
      "returning": 76,
      "totalAttendance": 377,
      "members": 584,
      "newFY": 71,
      "stillIn": 516,
      "alumni": 67,
      "gradUnknown": 1,
      "projects": 14
    },
    {
      "id": 2534,
      "name": "Sahrdaya College of Advanced Studies, Kodakara",
      "district": "thrissur",
      "events": 5,
      "types": {
        "Learning_Program": 2,
        "Meetup": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 116,
      "returning": 59,
      "totalAttendance": 192,
      "members": 290,
      "newFY": 104,
      "stillIn": 269,
      "alumni": 21,
      "gradUnknown": 0,
      "projects": 7
    },
    {
      "id": 1676,
      "name": "Sahrdaya College of Engineering & Technology, Kodakara",
      "district": "thrissur",
      "events": 13,
      "types": {
        "Learning_Program": 10,
        "Meetup": 1,
        "Talk_Session": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 33,
      "returning": 19,
      "totalAttendance": 96,
      "members": 1020,
      "newFY": 345,
      "stillIn": 954,
      "alumni": 64,
      "gradUnknown": 2,
      "projects": 2
    },
    {
      "id": 2148,
      "name": "Saintgits College of Applied Sciences, Pathamuttam",
      "district": "kottayam",
      "events": 5,
      "types": {
        "Learning_Program": 2,
        "Hackathon": 3
      },
      "uniqueAttendees": 82,
      "returning": 59,
      "totalAttendance": 153,
      "members": 120,
      "newFY": 113,
      "stillIn": 116,
      "alumni": 4,
      "gradUnknown": 0,
      "projects": 4
    },
    {
      "id": 2164,
      "name": "Saintgits College of Engineering, Pathamuttom",
      "district": "kottayam",
      "events": 7,
      "types": {
        "Meetup": 3,
        "Hackathon": 1,
        "Bootcamp": 1,
        "Core_Team_Meeting": 2
      },
      "uniqueAttendees": 56,
      "returning": 15,
      "totalAttendance": 91,
      "members": 750,
      "newFY": 120,
      "stillIn": 683,
      "alumni": 67,
      "gradUnknown": 0,
      "projects": 33
    },
    {
      "id": 2908,
      "name": "School of Engineering CUSAT, Kalamassery",
      "district": "ernakulam",
      "events": 7,
      "types": {
        "Workshop": 1,
        "Talk_Session": 2,
        "Learning_Program": 3,
        "Meetup": 1
      },
      "uniqueAttendees": 129,
      "returning": 41,
      "totalAttendance": 194,
      "members": 2428,
      "newFY": 177,
      "stillIn": 1986,
      "alumni": 440,
      "gradUnknown": 2,
      "projects": 58
    },
    {
      "id": 2081,
      "name": "SCMS School of Engineering & Technology, Karukutty",
      "district": "ernakulam",
      "events": 8,
      "types": {
        "Learning_Program": 1,
        "Meetup": 4,
        "Core_Team_Meeting": 3
      },
      "uniqueAttendees": 156,
      "returning": 17,
      "totalAttendance": 189,
      "members": 1335,
      "newFY": 283,
      "stillIn": 1266,
      "alumni": 67,
      "gradUnknown": 2,
      "projects": 30
    },
    {
      "id": 2084,
      "name": "SNM Institute of Management & Technology, Maliankara",
      "district": "ernakulam",
      "events": 12,
      "types": {
        "Meetup": 3,
        "Learning_Program": 2,
        "Workshop": 1,
        "Core_Team_Meeting": 5,
        "Talk_Session": 1
      },
      "uniqueAttendees": 159,
      "returning": 63,
      "totalAttendance": 291,
      "members": 455,
      "newFY": 40,
      "stillIn": 427,
      "alumni": 24,
      "gradUnknown": 4,
      "projects": 3
    },
    {
      "id": 2423,
      "name": "Sree Buddha College of Engineering, Pattoor",
      "district": "alappuzha",
      "events": 24,
      "types": {
        "Learning_Program": 14,
        "Talk_Session": 1,
        "Meetup": 3,
        "Core_Team_Meeting": 5,
        "Hackathon": 1
      },
      "uniqueAttendees": 128,
      "returning": 74,
      "totalAttendance": 352,
      "members": 351,
      "newFY": 137,
      "stillIn": 337,
      "alumni": 14,
      "gradUnknown": 0,
      "projects": 17
    },
    {
      "id": 2419,
      "name": "Sree Chitra Thirunal College of Engineering, Pappanamcode",
      "district": "thiruvananthapuram",
      "events": 2,
      "types": {
        "Workshop": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 52,
      "returning": 3,
      "totalAttendance": 55,
      "members": 520,
      "newFY": 30,
      "stillIn": 485,
      "alumni": 34,
      "gradUnknown": 1,
      "projects": 2
    },
    {
      "id": 2216,
      "name": "Sree Narayana Guru College of Engineering & Technology, Chalakode",
      "district": "kannur",
      "events": 13,
      "types": {
        "Workshop": 2,
        "Meetup": 2,
        "Core_Team_Meeting": 2,
        "Learning_Program": 5,
        "Talk_Session": 2
      },
      "uniqueAttendees": 234,
      "returning": 51,
      "totalAttendance": 354,
      "members": 326,
      "newFY": 284,
      "stillIn": 321,
      "alumni": 5,
      "gradUnknown": 0,
      "projects": 2
    },
    {
      "id": 2083,
      "name": "Sree Narayana Gurukulam College of Engineering, Kadayiruppu",
      "district": "ernakulam",
      "events": 3,
      "types": {
        "Talk_Session": 1,
        "Meetup": 1,
        "Learning_Program": 1
      },
      "uniqueAttendees": 136,
      "returning": 6,
      "totalAttendance": 142,
      "members": 375,
      "newFY": 124,
      "stillIn": 345,
      "alumni": 30,
      "gradUnknown": 0,
      "projects": 3
    },
    {
      "id": 2914,
      "name": "St. Joseph's College Devagiri",
      "district": "kozhikode",
      "events": 1,
      "types": {
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 0,
      "returning": 0,
      "totalAttendance": 0,
      "members": 349,
      "newFY": 38,
      "stillIn": 290,
      "alumni": 54,
      "gradUnknown": 5,
      "projects": 6
    },
    {
      "id": 2165,
      "name": "St. Josephs College of Engineering and Technology, Choondacherry",
      "district": "kottayam",
      "events": 2,
      "types": {
        "Learning_Program": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 2,
      "returning": 0,
      "totalAttendance": 2,
      "members": 383,
      "newFY": 102,
      "stillIn": 346,
      "alumni": 35,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 1959,
      "name": "St.Thomas College, Ranni",
      "district": "pathanamthitta",
      "events": 5,
      "types": {
        "Core_Team_Meeting": 2,
        "Workshop": 1,
        "Learning_Program": 2
      },
      "uniqueAttendees": 48,
      "returning": 19,
      "totalAttendance": 73,
      "members": 25,
      "newFY": 13,
      "stillIn": 24,
      "alumni": 1,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 1673,
      "name": "Thejus College Engineering College, Erumapetti",
      "district": "thrissur",
      "events": 3,
      "types": {
        "Core_Team_Meeting": 1,
        "Talk_Session": 2
      },
      "uniqueAttendees": 75,
      "returning": 0,
      "totalAttendance": 75,
      "members": 229,
      "newFY": 33,
      "stillIn": 215,
      "alumni": 14,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 2357,
      "name": "TKM College of Engineering, Karicode",
      "district": "kollam",
      "events": 6,
      "types": {
        "Meetup": 1,
        "Talk_Session": 1,
        "Core_Team_Meeting": 4
      },
      "uniqueAttendees": 62,
      "returning": 7,
      "totalAttendance": 81,
      "members": 867,
      "newFY": 66,
      "stillIn": 806,
      "alumni": 59,
      "gradUnknown": 2,
      "projects": 1
    },
    {
      "id": 2614,
      "name": "Toc H Institute of Science & Technology, Arakkunnam",
      "district": "ernakulam",
      "events": 8,
      "types": {
        "Learning_Program": 3,
        "Core_Team_Meeting": 2,
        "Meetup": 3
      },
      "uniqueAttendees": 129,
      "returning": 37,
      "totalAttendance": 204,
      "members": 889,
      "newFY": 129,
      "stillIn": 836,
      "alumni": 51,
      "gradUnknown": 2,
      "projects": 13
    },
    {
      "id": 1797,
      "name": "Unity Women's College, Manjeri",
      "district": "malappuram",
      "events": 8,
      "types": {
        "Learning_Program": 4,
        "Meetup": 2,
        "Talk_Session": 1,
        "Core_Team_Meeting": 1
      },
      "uniqueAttendees": 95,
      "returning": 29,
      "totalAttendance": 162,
      "members": 179,
      "newFY": 69,
      "stillIn": 170,
      "alumni": 9,
      "gradUnknown": 0,
      "projects": 1
    },
    {
      "id": 1670,
      "name": "Vidya Academy of Science & Technology, Thalakkottukara",
      "district": "thrissur",
      "events": 8,
      "types": {
        "Talk_Session": 1,
        "Learning_Program": 7
      },
      "uniqueAttendees": 267,
      "returning": 76,
      "totalAttendance": 369,
      "members": 581,
      "newFY": 226,
      "stillIn": 538,
      "alumni": 42,
      "gradUnknown": 1,
      "projects": 3
    },
    {
      "id": 2217,
      "name": "Vimal Jyothi Engineering College, Chemperi",
      "district": "kannur",
      "events": 3,
      "types": {
        "Hackathon": 1,
        "Core_Team_Meeting": 1,
        "Meetup": 1
      },
      "uniqueAttendees": 78,
      "returning": 10,
      "totalAttendance": 88,
      "members": 175,
      "newFY": 120,
      "stillIn": 155,
      "alumni": 20,
      "gradUnknown": 0,
      "projects": 32
    },
    {
      "id": 2085,
      "name": "Viswajyothi College of Engineering and Technology, Vazhakulam",
      "district": "ernakulam",
      "events": 6,
      "types": {
        "Learning_Program": 2,
        "Core_Team_Meeting": 2,
        "Meetup": 2
      },
      "uniqueAttendees": 40,
      "returning": 6,
      "totalAttendance": 46,
      "members": 867,
      "newFY": 127,
      "stillIn": 743,
      "alumni": 123,
      "gradUnknown": 1,
      "projects": 18
    }
  ]
};
