// Auto-generated daily by the mail-update scheduled task.
// Do NOT hand-edit — this file is overwritten on each run.
window.DASHBOARD_DATA = {
  "generatedAt": "2026-08-02",
  "threads": [
    {
      "id": "campus-bec26f19a9",
      "group": "campus",
      "subject": "Founding 100 for TinkerHub's campus maker communities",
      "counterpart": "manit@waycode.in",
      "email": "manit@waycode.in",
      "received": "2026-08-02",
      "last": "2026-08-02",
      "status": "No response",
      "note": "Cold outreach pitch from Waycode founder",
      "daysOpen": 0,
      "daysSinceReceived": 0
    },
    {
      "id": "campus-f736a4517e",
      "group": "campus",
      "subject": "Invitation: Advisory Committee Catchup",
      "counterpart": "internal (Habeeb)",
      "email": null,
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "Informational",
      "note": "Calendar invite",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "campus-62bc27a283",
      "group": "campus",
      "subject": "Date clash situation for Useless Projects",
      "counterpart": "ashishmathewpanakkal9c@gmail.com",
      "email": "ashishmathewpanakkal9c@gmail.com",
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "No response",
      "note": "Awaiting our slot decision",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "campus-c4ded824f1",
      "group": "campus",
      "subject": "Thank You for Being Part of Chaayem Puppsum",
      "counterpart": "community (bulk)",
      "email": null,
      "received": "2026-07-31",
      "last": "2026-07-31",
      "status": "Informational",
      "note": "Outbound thank-you note",
      "daysOpen": 2,
      "daysSinceReceived": 2
    },
    {
      "id": "campus-c2d4a8a14a",
      "group": "campus",
      "subject": "Re: Request for a Chief Guest \u2013 TinkerHub JCET Inauguration",
      "counterpart": "shaamilaashahul@gmail.com",
      "email": "shaamilaashahul@gmail.com",
      "received": "2026-07-31",
      "last": "2026-07-31",
      "status": "Resolved",
      "note": "Confirmed attendance Aug 5",
      "daysOpen": 2,
      "daysSinceReceived": 2
    },
    {
      "id": "campus-fad7c25d96",
      "group": "campus",
      "subject": "Request for Industrial Visit \u2013 Malabar College of Advanced Studies",
      "counterpart": "arshad@malabarcollegevengara.org",
      "email": "arshad@malabarcollegevengara.org",
      "received": "2026-07-31",
      "last": "2026-08-01",
      "status": "Resolved",
      "note": "Registration completed for Aug 13 visit",
      "daysOpen": 1,
      "daysSinceReceived": 2
    },
    {
      "id": "campus-b413e50ab7",
      "group": "campus",
      "subject": "URGENT: Request for Intervention - Jai Bharath College",
      "counterpart": "mohammedihsantk@gmail.com",
      "email": "mohammedihsantk@gmail.com",
      "received": "2026-07-30",
      "last": "2026-07-31",
      "status": "Awaiting reply (from us)",
      "note": "We owe them a confirmed visit date",
      "daysOpen": 2,
      "daysSinceReceived": 3
    },
    {
      "id": "campus-180b71ff21",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Irvin)",
      "counterpart": "irvin.snj@gmail.com",
      "email": "irvin.snj@gmail.com",
      "received": "2026-07-30",
      "last": "2026-07-30",
      "status": "Informational",
      "note": "",
      "daysOpen": 3,
      "daysSinceReceived": 3
    },
    {
      "id": "campus-acc3ff68af",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Sidharth)",
      "counterpart": "itssid2001@gmail.com",
      "email": "itssid2001@gmail.com",
      "received": "2026-07-30",
      "last": "2026-07-30",
      "status": "Informational",
      "note": "",
      "daysOpen": 3,
      "daysSinceReceived": 3
    },
    {
      "id": "campus-b562ec9adb",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Ziyan)",
      "counterpart": "mziyan777.mz@gmail.com",
      "email": "mziyan777.mz@gmail.com",
      "received": "2026-07-30",
      "last": "2026-07-30",
      "status": "Informational",
      "note": "",
      "daysOpen": 3,
      "daysSinceReceived": 3
    },
    {
      "id": "campus-28730e984b",
      "group": "campus",
      "subject": "TinkerHub x LOUD - Something exciting could brew",
      "counterpart": "goloudindia90@gmail.com",
      "email": "goloudindia90@gmail.com",
      "received": "2026-07-29",
      "last": "2026-07-30",
      "status": "Awaiting reply (from them)",
      "note": "Femina proposed a meeting time, no confirmation yet",
      "daysOpen": 3,
      "daysSinceReceived": 4
    },
    {
      "id": "campus-df33971778",
      "group": "campus",
      "subject": "Request for Support and Participation in IEDC MBCCET Event",
      "counterpart": "6222@mbcpeermade.com",
      "email": "6222@mbcpeermade.com",
      "received": "2026-07-27",
      "last": "2026-07-29",
      "status": "Awaiting reply (from them)",
      "note": "We asked for more event details",
      "daysOpen": 4,
      "daysSinceReceived": 6
    },
    {
      "id": "campus-180706a1f8",
      "group": "campus",
      "subject": "Request for another letter due to change of principal",
      "counterpart": "tinkerhubcep@gmail.com",
      "email": "tinkerhubcep@gmail.com",
      "received": "2026-07-27",
      "last": "2026-07-27",
      "status": "No response",
      "note": "",
      "daysOpen": 6,
      "daysSinceReceived": 6
    },
    {
      "id": "campus-96cf189a13",
      "group": "campus",
      "subject": "TinkerHub: Invitation to Speak at Chaayem Puppsum (Irvin)",
      "counterpart": "irvin.snj@gmail.com",
      "email": "irvin.snj@gmail.com",
      "received": "2026-07-23",
      "last": "2026-07-23",
      "status": "Informational",
      "note": "",
      "daysOpen": 10,
      "daysSinceReceived": 10
    },
    {
      "id": "campus-22e63d934b",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Siddarth)",
      "counterpart": "itssid2001@gmail.com",
      "email": "itssid2001@gmail.com",
      "received": "2026-07-23",
      "last": "2026-07-23",
      "status": "Resolved",
      "note": "",
      "daysOpen": 10,
      "daysSinceReceived": 10
    },
    {
      "id": "campus-cc3c2d5a81",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Athul)",
      "counterpart": "athul111@gmail.com",
      "email": "athul111@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-b0cf04ea25",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Siddarth/FOSS United)",
      "counterpart": "siddharth@fossunited.org",
      "email": "siddharth@fossunited.org",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-ce0b466747",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Sachin)",
      "counterpart": "sachin@mulearn.org",
      "email": "sachin@mulearn.org",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Resolved",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-108548cbcb",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Mujeeb)",
      "counterpart": "mujeeblatheef.in@gmail.com",
      "email": "mujeeblatheef.in@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-006b16c0b5",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Akshat)",
      "counterpart": "akpradeep4a@gmail.com",
      "email": "akpradeep4a@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-ab709a3547",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Achuth)",
      "counterpart": "achuthan1176@gmail.com",
      "email": "achuthan1176@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-a98b696501",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Safeer)",
      "counterpart": "safeerussalamms@gmail.com",
      "email": "safeerussalamms@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Resolved",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-a33117e554",
      "group": "campus",
      "subject": "Thank You for Speaking at Chaayem Puppsum (Sreedan)",
      "counterpart": "sreedanskumar2006@gmail.com",
      "email": "sreedanskumar2006@gmail.com",
      "received": "2026-07-21",
      "last": "2026-07-21",
      "status": "Informational",
      "note": "",
      "daysOpen": 12,
      "daysSinceReceived": 12
    },
    {
      "id": "campus-aa0cc9099b",
      "group": "campus",
      "subject": "Your Mentimeter receipt",
      "counterpart": "Mentimeter (automated)",
      "email": null,
      "received": "2026-07-19",
      "last": "2026-07-19",
      "status": "Informational",
      "note": "",
      "daysOpen": 14,
      "daysSinceReceived": 14
    },
    {
      "id": "campus-5aeed4f3de",
      "group": "campus",
      "subject": "Request to conduct Industrial Visit \u2013 Providence College",
      "counterpart": "libin.cs25057@student.providence.edu.in",
      "email": "libin.cs25057@student.providence.edu.in",
      "received": "2026-07-18",
      "last": "2026-07-21",
      "status": "Awaiting reply (from us)",
      "note": "Internal handoff to Shan, no closure yet",
      "daysOpen": 12,
      "daysSinceReceived": 15
    },
    {
      "id": "campus-58693d11f7",
      "group": "campus",
      "subject": "Change of Faculty Coordinator: KAHM Unity Women's College Manjeri",
      "counterpart": "fathimaafrahpp@gmail.com",
      "email": "fathimaafrahpp@gmail.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "No response",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-e921cdce72",
      "group": "campus",
      "subject": "Tinkerhub: Welcome to the Campus Council (Fahad)",
      "counterpart": "mofahadkp@proton.me",
      "email": "mofahadkp@proton.me",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Informational",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-997dd4f05d",
      "group": "campus",
      "subject": "Tinkerhub: Welcome to the Campus Council (Salha)",
      "counterpart": "salhamkhalfan@gmail.com",
      "email": "salhamkhalfan@gmail.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Informational",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-9f5b3d6402",
      "group": "campus",
      "subject": "TinkerHub: NSS Report 2024-2026",
      "counterpart": "adithyavijay04@gmail.com",
      "email": "adithyavijay04@gmail.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Informational",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-138e3d459e",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Akshat)",
      "counterpart": "akpradeep4a@gmail.com",
      "email": "akpradeep4a@gmail.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Resolved",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-9735aea37a",
      "group": "campus",
      "subject": "Request for Camp Slot Shift to Kozhikode \u2013 Jai Bharath College",
      "counterpart": "mohammedihsantk@gmail.com",
      "email": "mohammedihsantk@gmail.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Resolved",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "campus-6e773953a5",
      "group": "campus",
      "subject": "Request to Reschedule Chaayem Puppsum Slot (Abdul Samad)",
      "counterpart": "abdulsamadcv2007@gmail.com",
      "email": "abdulsamadcv2007@gmail.com",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "Resolved",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-ef665c532e",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Safeer)",
      "counterpart": "safeerussalamms@gmail.com",
      "email": "safeerussalamms@gmail.com",
      "received": "2026-07-16",
      "last": "2026-07-17",
      "status": "Resolved",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-6c113c2520",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Sreedan)",
      "counterpart": "sreedanskumar2006@gmail.com",
      "email": "sreedanskumar2006@gmail.com",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "Informational",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-99317e20f8",
      "group": "campus",
      "subject": "TinkerHub: Invitation to Speak at Chaayem Puppsum (Manoj)",
      "counterpart": "manoj@sahya.org.in",
      "email": "manoj@sahya.org.in",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "Informational",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-558dc1d4e6",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Siddarth/FOSS United)",
      "counterpart": "siddharth@fossunited.org",
      "email": "siddharth@fossunited.org",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "Resolved",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-ec42fc391d",
      "group": "campus",
      "subject": "Request for TinkerHub Orientation Session (Thejus Engineering College)",
      "counterpart": "dhrisyanarayanan7@gmail.com",
      "email": "dhrisyanarayanan7@gmail.com",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "No response",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-e2a82d641b",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Ziyan)",
      "counterpart": "mziyan777.mz@gmail.com",
      "email": "mziyan777.mz@gmail.com",
      "received": "2026-07-16",
      "last": "2026-07-16",
      "status": "Informational",
      "note": "",
      "daysOpen": 17,
      "daysSinceReceived": 17
    },
    {
      "id": "campus-637ec274a7",
      "group": "campus",
      "subject": "Request to Bring Additional Visitors to TinkerSpace",
      "counterpart": "anjalispillai321@gmail.com",
      "email": "anjalispillai321@gmail.com",
      "received": "2026-07-14",
      "last": "2026-07-14",
      "status": "No response",
      "note": "",
      "daysOpen": 19,
      "daysSinceReceived": 19
    },
    {
      "id": "campus-cc6b25a31f",
      "group": "campus",
      "subject": "Courier Received in Damaged Condition",
      "counterpart": "jualajum6@gmail.com",
      "email": "jualajum6@gmail.com",
      "received": "2026-07-11",
      "last": "2026-07-11",
      "status": "No response",
      "note": "",
      "daysOpen": 22,
      "daysSinceReceived": 22
    },
    {
      "id": "campus-6814dee1bd",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Shone)",
      "counterpart": "shone.jose@ieee.org",
      "email": "shone.jose@ieee.org",
      "received": "2026-07-10",
      "last": "2026-07-10",
      "status": "Informational",
      "note": "",
      "daysOpen": 23,
      "daysSinceReceived": 23
    },
    {
      "id": "campus-3330e231ca",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Thomaskutty)",
      "counterpart": "thomaskutty@ieee.org",
      "email": "thomaskutty@ieee.org",
      "received": "2026-07-08",
      "last": "2026-07-08",
      "status": "Informational",
      "note": "",
      "daysOpen": 25,
      "daysSinceReceived": 25
    },
    {
      "id": "campus-7bc99ef404",
      "group": "campus",
      "subject": "TinkerHub: Confirmation for Chaayem Puppsum (Sachin)",
      "counterpart": "sachin@mulearn.org",
      "email": "sachin@mulearn.org",
      "received": "2026-07-08",
      "last": "2026-07-08",
      "status": "Resolved",
      "note": "",
      "daysOpen": 25,
      "daysSinceReceived": 25
    },
    {
      "id": "campus-ea8e03d821",
      "group": "campus",
      "subject": "Proof of being Campus Lead",
      "counterpart": "26mba370@iimraipur.ac.in",
      "email": "26mba370@iimraipur.ac.in",
      "received": "2026-07-02",
      "last": "2026-07-08",
      "status": "Resolved",
      "note": "",
      "daysOpen": 25,
      "daysSinceReceived": 31
    },
    {
      "id": "campus-0f11861e10",
      "group": "campus",
      "subject": "TinkerHub: Chayeem Puppsum is here! (Anupama)",
      "counterpart": "anupamaanilammus@gmail.com",
      "email": "anupamaanilammus@gmail.com",
      "received": "2026-07-05",
      "last": "2026-07-08",
      "status": "Resolved",
      "note": "",
      "daysOpen": 25,
      "daysSinceReceived": 28
    },
    {
      "id": "campus-3a44930c9e",
      "group": "campus",
      "subject": "TinkerHub: Chayeem Puppsum is here! (Ann Rose/Abhirag/Pooja/Anjali)",
      "counterpart": "multiple students",
      "email": null,
      "received": "2026-07-05",
      "last": "2026-07-15",
      "status": "Resolved",
      "note": "",
      "daysOpen": 18,
      "daysSinceReceived": 28
    },
    {
      "id": "campus-66b192b49c",
      "group": "campus",
      "subject": "TinkerHub: Chayeem Puppsum is here! (Swathy)",
      "counterpart": "swathy062006@gmail.com",
      "email": "swathy062006@gmail.com",
      "received": "2026-07-05",
      "last": "2026-07-08",
      "status": "Resolved",
      "note": "",
      "daysOpen": 25,
      "daysSinceReceived": 28
    },
    {
      "id": "campus-64a9a3909a",
      "group": "campus",
      "subject": "Invitation: Class of 24 - catchup",
      "counterpart": "internal (Habeeb)",
      "email": null,
      "received": "2026-07-04",
      "last": "2026-07-04",
      "status": "Informational",
      "note": "Calendar invite",
      "daysOpen": 29,
      "daysSinceReceived": 29
    },
    {
      "id": "campus-9c89b65996",
      "group": "campus",
      "subject": "TINKERHUB: Important details for Onboarding Camp",
      "counterpart": "cohort (bulk)",
      "email": null,
      "received": "2026-07-03",
      "last": "2026-07-03",
      "status": "Informational",
      "note": "",
      "daysOpen": 30,
      "daysSinceReceived": 30
    },
    {
      "id": "support-11754e3e4c",
      "group": "support",
      "subject": "Enquiry About Changing Discord Accounts",
      "counterpart": "navaneeth0930@gmail.com",
      "email": "navaneeth0930@gmail.com",
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "No response",
      "note": "",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "support-d273010645",
      "group": "support",
      "subject": "Request to Correct Date of Birth",
      "counterpart": "sinannkhalid@gmail.com",
      "email": "sinannkhalid@gmail.com",
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "No response",
      "note": "",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "support-62b6e23884",
      "group": "support",
      "subject": "Request for Access to TinkerHub Discord Server (RIT Kottayam)",
      "counterpart": "dayroansajii17@gmail.com",
      "email": "dayroansajii17@gmail.com",
      "received": "2026-07-29",
      "last": "2026-07-29",
      "status": "No response",
      "note": "",
      "daysOpen": 4,
      "daysSinceReceived": 4
    },
    {
      "id": "support-f6c7cc5123",
      "group": "support",
      "subject": "Unable to use vouch/invite sent by friend",
      "counterpart": "julinshaji01@gmail.com",
      "email": "julinshaji01@gmail.com",
      "received": "2026-07-25",
      "last": "2026-07-25",
      "status": "No response",
      "note": "",
      "daysOpen": 8,
      "daysSinceReceived": 8
    },
    {
      "id": "support-3a40af0a01",
      "group": "support",
      "subject": "I put wrong date of birth, now in kuttymaker",
      "counterpart": "sinannkhalid@gmail.com",
      "email": "sinannkhalid@gmail.com",
      "received": "2026-07-19",
      "last": "2026-07-19",
      "status": "No response",
      "note": "Earlier report of same recurring DOB issue",
      "daysOpen": 14,
      "daysSinceReceived": 14
    },
    {
      "id": "support-59927728ec",
      "group": "support",
      "subject": "Change of current Discord account removal",
      "counterpart": "mail@vishnudileesh.com",
      "email": "mail@vishnudileesh.com",
      "received": "2026-07-17",
      "last": "2026-07-17",
      "status": "Resolved",
      "note": "",
      "daysOpen": 16,
      "daysSinceReceived": 16
    },
    {
      "id": "support-b486a5c5e9",
      "group": "support",
      "subject": "Re: I want to delete my account",
      "counterpart": "sinannkhalid@gmail.com",
      "email": "sinannkhalid@gmail.com",
      "received": "2026-07-15",
      "last": "2026-07-15",
      "status": "No response",
      "note": "Follow-up providing account phone number",
      "daysOpen": 18,
      "daysSinceReceived": 18
    },
    {
      "id": "support-7049726065",
      "group": "support",
      "subject": "Certificate Name Issue",
      "counterpart": "hamdanmmji@gmail.com",
      "email": "hamdanmmji@gmail.com",
      "received": "2026-04-30",
      "last": "2026-07-11",
      "status": "Awaiting reply (from them)",
      "note": "We replied; no confirmation from user",
      "daysOpen": 22,
      "daysSinceReceived": 94
    },
    {
      "id": "support-e996065e55",
      "group": "support",
      "subject": "Issue with Login and OTP Verification",
      "counterpart": "bijobiju2022@gmail.com",
      "email": "bijobiju2022@gmail.com",
      "received": "2026-06-23",
      "last": "2026-07-11",
      "status": "Awaiting reply (from them)",
      "note": "We asked if issue still persists",
      "daysOpen": 22,
      "daysSinceReceived": 40
    },
    {
      "id": "support-f04dea8c8c",
      "group": "support",
      "subject": "Unable to Make TinkerHub Profile Public",
      "counterpart": "aathirasagar9@gmail.com",
      "email": "aathirasagar9@gmail.com",
      "received": "2026-07-10",
      "last": "2026-07-11",
      "status": "Resolved",
      "note": "",
      "daysOpen": 22,
      "daysSinceReceived": 23
    },
    {
      "id": "support-affc67ef65",
      "group": "support",
      "subject": "Finished the old project (add new project option)",
      "counterpart": "adarshsbabu2003@gmail.com",
      "email": "adarshsbabu2003@gmail.com",
      "received": "2026-07-08",
      "last": "2026-07-11",
      "status": "Awaiting reply (from them)",
      "note": "We answered; no confirmation from user",
      "daysOpen": 22,
      "daysSinceReceived": 25
    },
    {
      "id": "finance-017a5a96ad",
      "group": "finance",
      "subject": "Amazon Web Services GST Invoice Available",
      "counterpart": "AWS (automated)",
      "email": null,
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "Informational",
      "note": "",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "finance-0b37ac67ed",
      "group": "finance",
      "subject": "MSG91 Subscription Renewal Summary",
      "counterpart": "MSG91 (automated)",
      "email": null,
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "Informational",
      "note": "",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "finance-7a70ace0ee",
      "group": "finance",
      "subject": "Re: Meshaaq July'26 HK invoice",
      "counterpart": "meshaaq@outlook.com",
      "email": "meshaaq@outlook.com",
      "received": "2026-08-01",
      "last": "2026-08-01",
      "status": "Resolved",
      "note": "Payment settled",
      "daysOpen": 1,
      "daysSinceReceived": 1
    },
    {
      "id": "finance-833c41682e",
      "group": "finance",
      "subject": "Moderator's spam report for finance@tinkerhub.org",
      "counterpart": "Google Groups (automated)",
      "email": null,
      "received": "2026-07-31",
      "last": "2026-07-31",
      "status": "Informational",
      "note": "",
      "daysOpen": 2,
      "daysSinceReceived": 2
    },
    {
      "id": "finance-82e3aa82ff",
      "group": "finance",
      "subject": "Invoice for month of July, 2026",
      "counterpart": "chinnnu.susan@gmail.com",
      "email": "chinnnu.susan@gmail.com",
      "received": "2026-07-31",
      "last": "2026-08-01",
      "status": "Resolved",
      "note": "Payment settled, thanked",
      "daysOpen": 1,
      "daysSinceReceived": 2
    },
    {
      "id": "finance-5b9691d92e",
      "group": "finance",
      "subject": "INVOICE - JULY 2026",
      "counterpart": "hrdsss2007@gmail.com",
      "email": "hrdsss2007@gmail.com",
      "received": "2026-07-28",
      "last": "2026-07-31",
      "status": "Resolved",
      "note": "Payment settled",
      "daysOpen": 2,
      "daysSinceReceived": 5
    },
    {
      "id": "finance-ccb2bae237",
      "group": "finance",
      "subject": "Tink Her Hack Research Article Invoice",
      "counterpart": "connect.npoc@gmail.com",
      "email": "connect.npoc@gmail.com",
      "received": "2026-07-22",
      "last": "2026-07-23",
      "status": "Resolved",
      "note": "Payment settled",
      "daysOpen": 10,
      "daysSinceReceived": 11
    },
    {
      "id": "finance-40c2a53da0",
      "group": "finance",
      "subject": "Your receipt from Resend",
      "counterpart": "Resend (automated)",
      "email": null,
      "received": "2026-07-06",
      "last": "2026-07-06",
      "status": "Informational",
      "note": "",
      "daysOpen": 27,
      "daysSinceReceived": 27
    },
    {
      "id": "finance-7ac2fafcfb",
      "group": "finance",
      "subject": "Invoice Settlement: CDPC2627/636 and CDPC2627/643",
      "counterpart": "cprint4me@gmail.com",
      "email": "cprint4me@gmail.com",
      "received": "2026-07-04",
      "last": "2026-07-04",
      "status": "Awaiting reply (from them)",
      "note": "Asked vendor to confirm receipt",
      "daysOpen": 29,
      "daysSinceReceived": 29
    },
    {
      "id": "finance-705c14b7f7",
      "group": "finance",
      "subject": "Reimbursements & Bill Settlements - June",
      "counterpart": "mehar@tinkerhub.org (internal)",
      "email": null,
      "received": "2026-07-04",
      "last": "2026-07-04",
      "status": "Awaiting reply (from them)",
      "note": "Asked to confirm receipt",
      "daysOpen": 29,
      "daysSinceReceived": 29
    },
    {
      "id": "finance-abbc85dfeb",
      "group": "finance",
      "subject": "Meshaaq PMS June'26 HK invoice",
      "counterpart": "meshaaq@outlook.com",
      "email": "meshaaq@outlook.com",
      "received": "2026-07-04",
      "last": "2026-07-04",
      "status": "Resolved",
      "note": "Payment completed",
      "daysOpen": 29,
      "daysSinceReceived": 29
    },
    {
      "id": "report-698ff0dada",
      "group": "report",
      "subject": "(no subject)",
      "counterpart": "anumariya2684@gmail.com",
      "email": "anumariya2684@gmail.com",
      "received": "2026-07-30",
      "last": "2026-07-30",
      "status": "No response",
      "note": "No subject/body captured",
      "daysOpen": 3,
      "daysSinceReceived": 3
    },
    {
      "id": "report-65bbce117d",
      "group": "report",
      "subject": "Bsc computer science",
      "counterpart": "thensila75@gmail.com",
      "email": "thensila75@gmail.com",
      "received": "2026-07-14",
      "last": "2026-07-14",
      "status": "No response",
      "note": "",
      "daysOpen": 19,
      "daysSinceReceived": 19
    }
  ],
  "summary": {
    "No response": 15,
    "Informational": 27,
    "Resolved": 22,
    "Awaiting reply (from us)": 2,
    "Awaiting reply (from them)": 7
  },
  "analytics": {
    "campus": {
      "total": 49,
      "No response": 7,
      "Awaiting reply (from us)": 2,
      "Awaiting reply (from them)": 2,
      "Resolved": 15,
      "Informational": 23,
      "avgOpenDays": 9.3,
      "avgResolvedDays": 15.8
    },
    "support": {
      "total": 11,
      "No response": 6,
      "Awaiting reply (from us)": 0,
      "Awaiting reply (from them)": 3,
      "Resolved": 2,
      "Informational": 0,
      "avgOpenDays": 12.4,
      "avgResolvedDays": 19.0
    },
    "finance": {
      "total": 11,
      "No response": 0,
      "Awaiting reply (from us)": 0,
      "Awaiting reply (from them)": 2,
      "Resolved": 5,
      "Informational": 4,
      "avgOpenDays": 29.0,
      "avgResolvedDays": 8.6
    },
    "report": {
      "total": 2,
      "No response": 2,
      "Awaiting reply (from us)": 0,
      "Awaiting reply (from them)": 0,
      "Resolved": 0,
      "Informational": 0,
      "avgOpenDays": 11.0,
      "avgResolvedDays": null
    }
  }
};
