window.LINEAR_DATA = {
 "generatedAt": "2026-08-29",
 "workspace": "th-app",
 "team": "Devs",
 "teamTotals": {
  "total": 164,
  "backlog": 49,
  "todo": 10,
  "started": 8,
  "completed": 87,
  "canceled": 6,
  "duplicate": 4
 },
 "stuck": [
  {
   "id": "DEV-65",
   "title": "Update Kootam dashboard in production",
   "project": null,
   "status": "In Review",
   "assignee": null,
   "startedAt": "2026-04-30T11:26:35.758Z",
   "updatedAt": "2026-04-30T11:26:35.786Z",
   "url": "https://linear.app/th-app/issue/DEV-65/update-kootam-dashboard-in-production",
   "priority": "High",
   "daysSinceUpdate": 120,
   "daysSinceStarted": 120
  },
  {
   "id": "DEV-105",
   "title": "Firebase migration",
   "project": "Project Migration - Hoomans to TH",
   "status": "In Progress",
   "assignee": null,
   "startedAt": "2026-04-10T09:27:51.531Z",
   "updatedAt": "2026-05-01T10:09:27.862Z",
   "url": "https://linear.app/th-app/issue/DEV-105/firebase-migration",
   "priority": "No priority",
   "daysSinceUpdate": 119,
   "daysSinceStarted": 140
  },
  {
   "id": "DEV-104",
   "title": "Project based event",
   "project": null,
   "status": "In Review",
   "assignee": null,
   "startedAt": "2026-04-10T05:56:17.613Z",
   "updatedAt": "2026-05-03T05:00:35.647Z",
   "url": "https://linear.app/th-app/issue/DEV-104/project-based-event",
   "priority": "No priority",
   "daysSinceUpdate": 117,
   "daysSinceStarted": 140
  },
  {
   "id": "DEV-4",
   "title": "Project Based Events",
   "project": "Project Based Events",
   "status": "In Review",
   "assignee": "akhil@tinkerhub.org",
   "startedAt": "2026-04-02T06:39:50.807Z",
   "updatedAt": "2026-05-03T05:11:53.317Z",
   "url": "https://linear.app/th-app/issue/DEV-4/project-based-events",
   "priority": "High",
   "daysSinceUpdate": 117,
   "daysSinceStarted": 148
  },
  {
   "id": "DEV-123",
   "title": "Investigate OTP delivery failure for specific phone numbers",
   "project": "Comms",
   "status": "In Progress",
   "assignee": "akhil@tinkerhub.org",
   "startedAt": "2026-05-06T05:57:22.369Z",
   "updatedAt": "2026-05-07T14:44:27.814Z",
   "url": "https://linear.app/th-app/issue/DEV-123/investigate-otp-delivery-failure-for-specific-phone-numbers",
   "priority": "Medium",
   "daysSinceUpdate": 113,
   "daysSinceStarted": 114
  },
  {
   "id": "DEV-122",
   "title": "Switch profiles Koottam dashboard",
   "project": "Koottam",
   "status": "In Review",
   "assignee": "KJ Gopika",
   "startedAt": "2026-05-15T05:48:23.044Z",
   "updatedAt": "2026-05-15T05:48:23.057Z",
   "url": "https://linear.app/th-app/issue/DEV-122/switch-profiles-koottam-dashboard",
   "priority": "No priority",
   "daysSinceUpdate": 105,
   "daysSinceStarted": 105
  },
  {
   "id": "DEV-129",
   "title": "Handling OTP Responses from MSG91 in App",
   "project": "Comms",
   "status": "In Progress",
   "assignee": "akhil@tinkerhub.org",
   "startedAt": "2026-05-16T07:54:40.223Z",
   "updatedAt": "2026-05-17T17:42:02.565Z",
   "url": "https://linear.app/th-app/issue/DEV-129/handling-otp-responses-from-msg91-in-app",
   "priority": "No priority",
   "daysSinceUpdate": 103,
   "daysSinceStarted": 104
  },
  {
   "id": "DEV-75",
   "title": "Tagging mentors for specific events",
   "project": "Adding Mentors",
   "status": "In Review",
   "assignee": null,
   "startedAt": "2026-05-16T08:26:14.267Z",
   "updatedAt": "2026-05-22T12:34:21.511Z",
   "url": "https://linear.app/th-app/issue/DEV-75/tagging-mentors-for-specific-events",
   "priority": "Medium",
   "daysSinceUpdate": 98,
   "daysSinceStarted": 104
  }
 ],
 "projects": [
  {
   "name": "Opportunities",
   "lead": null,
   "projectStatus": "Backlog",
   "total": 19,
   "backlog": 19,
   "todo": 0,
   "started": 0,
   "completed": 0,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Comms",
   "lead": null,
   "projectStatus": "Backlog",
   "total": 10,
   "backlog": 3,
   "todo": 0,
   "started": 2,
   "completed": 4,
   "canceled": 1,
   "duplicate": 0
  },
  {
   "name": "Process Improvements",
   "lead": "KJ Gopika",
   "projectStatus": "Backlog",
   "total": 9,
   "backlog": 1,
   "todo": 1,
   "started": 0,
   "completed": 7,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Project Based Events",
   "lead": "KJ Gopika",
   "projectStatus": "Backlog",
   "total": 8,
   "backlog": 2,
   "todo": 0,
   "started": 1,
   "completed": 4,
   "canceled": 1,
   "duplicate": 0
  },
  {
   "name": "Koottam",
   "lead": "KJ Gopika",
   "projectStatus": "Backlog",
   "total": 7,
   "backlog": 2,
   "todo": 0,
   "started": 1,
   "completed": 3,
   "canceled": 1,
   "duplicate": 0
  },
  {
   "name": "Project Migration - Hoomans to TH",
   "lead": null,
   "projectStatus": "In Progress",
   "total": 7,
   "backlog": 0,
   "todo": 1,
   "started": 1,
   "completed": 5,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Adding Mentors",
   "lead": "KJ Gopika",
   "projectStatus": "Backlog",
   "total": 5,
   "backlog": 3,
   "todo": 0,
   "started": 1,
   "completed": 1,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Data Change Requests",
   "lead": null,
   "projectStatus": "Backlog",
   "total": 3,
   "backlog": 0,
   "todo": 0,
   "started": 0,
   "completed": 2,
   "canceled": 1,
   "duplicate": 0
  },
  {
   "name": "Tinkerspace",
   "lead": "KJ Gopika",
   "projectStatus": "Backlog",
   "total": 2,
   "backlog": 1,
   "todo": 1,
   "started": 0,
   "completed": 0,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Donor Workflow",
   "lead": null,
   "projectStatus": "Backlog",
   "total": 1,
   "backlog": 1,
   "todo": 0,
   "started": 0,
   "completed": 0,
   "canceled": 0,
   "duplicate": 0
  },
  {
   "name": "Uncategorized (no project)",
   "lead": null,
   "projectStatus": null,
   "total": 93,
   "backlog": 17,
   "todo": 7,
   "started": 2,
   "completed": 61,
   "canceled": 2,
   "duplicate": 4
  }
 ]
};
